---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-client
  labels:
    death-star-project: social-network
    app: ubuntu-client
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: ubuntu-client
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: ubuntu-client
      name: ubuntu-client
    spec:
      containers:
      - name: ubuntu-client
        image: ubuntu
        command:  ["/bin/sh", "-c"]
        args:
          - apt-get -y update &&
            apt-get -y upgrade &&
            apt-get -y install dnsutils git vim python3 python3-aiohttp libssl-dev libz-dev luarocks iputils-ping lynx build-essential gcc bash curl &&
            luarocks install luasocket &&
            sleep 365d
        imagePullPolicy: Always
      restartPolicy: Always
