version: 1.0
provider:
  name: openfaas
  gateway: http://${MASTER_IP}:31112
functions:
  init-config-mongo:
    lang: java8
    handler: ./init-config-mongo
    image: ${DOCKER_USERNAME}/init-config-mongo:latest

