apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-serverless-ui-dashboard
spec:
  selector:
    matchLabels:
      app: ts-serverless-ui-dashboard
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-serverless-ui-dashboard
    spec:
      containers:
      - name: ts-serverless-ui-dashboard
        # image: registry.cn-shanghai.aliyuncs.com/akasakaisami/serverless_tt_frontend
        image: diomwu/serverless_tt_frontend:nginx-update
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi

---

apiVersion: v1
kind: Service
metadata:
  name: ts-serverless-ui-dashboard
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 32677
  selector:
   app: ts-serverless-ui-dashboard
---
