apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-auth-service
spec:
  selector:
    matchLabels:
      app: ts-auth-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-auth-service
    spec:
      containers:
      - name: ts-auth-service
        image: 286071421/ts-auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 12340
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        # readinessProbe:
        #   tcpSocket:
        #     port: 12340
        #   initialDelaySeconds: 160
        #   periodSeconds: 10
        #   timeoutSeconds: 5 
---

apiVersion: v1
kind: Service
metadata:
  name: ts-auth-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 12340
      nodePort: 30027
  selector:
   app: ts-auth-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-verification-code-service
spec:
  selector:
    matchLabels:
      app: ts-verification-code-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-verification-code-service
    spec:
      containers:
      - name: ts-verification-code-service
        image: 286071421/ts-verification-code-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 15678
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        # readinessProbe:
        #   tcpSocket:
        #     port: 15678
        #   initialDelaySeconds: 160
        #   periodSeconds: 10
        #   timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-verification-code-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 15678
      nodePort: 30026
  selector:
   app: ts-verification-code-service